name: Android

on:
  push:
    branches: [ korge ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew android:assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-android
          path: ./android/build/outputs/apk/release/*.apk
