name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # https://github.com/golang/go/wiki/Mobile
      - name: Install dependencies
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Link latest Android NDK
        run: |
          unlink "$ANDROID_NDK_HOME"
          ln -s "$ANDROID_NDK_LATEST_HOME" "$ANDROID_NDK_HOME"

      - name: Build
        run: |
          cp ./dist/android/AndroidManifest.xml .
          gomobile build -v -target=android/arm64 -androidapi=32 .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-android
          path: ./ubongo.apk
