name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use latest Android NDK
        run: |
          unlink "$ANDROID_NDK_HOME"
          ln -s "$ANDROID_NDK_LATEST_HOME" "$ANDROID_NDK_HOME"

      - name: Build
        run: ./gradlew android:assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-android
          path: ./android/build/outputs/apk/release/*.apk
