name: Android

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://docs.korge.org/korge/deployment/desktop
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install freeglut3-dev libopenal-dev

      - name: Prepare keystore
        env:
          KEYSTORE_FILE: ${{secrets.KEYSTORE_FILE}}
          KEYSTORE_PROPERTIES: ${{secrets.KEYSTORE_PROPERTIES}}
        run: |
          echo "$KEYSTORE_FILE" | base64 -di > "release.jks"
          echo "$KEYSTORE_PROPERTIES" > "key.properties"

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Build AAB
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew bundleRelease

      - name: Prepare filename (master)
        if: github.ref == 'refs/heads/master'
        working-directory: build/outputs/apk/release
        run: |
          HASH="$(git rev-parse --short HEAD)"
          mv "ubongo-release.apk" "ubongo-$HASH.apk"

      - name: Prepare filename (tag)
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: build/outputs/apk/release
        run: |
          TAG="$(git describe --abbrev=0 --tags)"
          mv "ubongo-release.apk" "ubongo-$TAG.apk"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-android
          path: |
            ./build/outputs/apk/release/*.apk
            ./build/outputs/bundle/release/*.aab

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/outputs/apk/release/ubongo-*.apk