name: Android

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://docs.korge.org/korge/deployment/desktop
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install freeglut3-dev libopenal-dev

      - name: Prepare keystore file
        env:
          KEYSTORE_FILE: ${{secrets.KEYSTORE_FILE}}
        run: echo "$KEYSTORE_FILE" | base64 -di > "release.jks"

      - name: Prepare keystore properties
        env:
          KEYSTORE_PROPERTIES: ${{secrets.KEYSTORE_PROPERTIES}}
        run: echo "$KEYSTORE_PROPERTIES" > "key.properties"

      - name: Build
        run: ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-android
          path: ./build/outputs/apk/release/*.apk
