name: Android

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://docs.korge.org/korge/deployment/desktop
      # Linux dependencies are also required for Android
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install freeglut3-dev libopenal-dev

      - name: Prepare keystore
        env:
          KEYSTORE_FILE: ${{secrets.KEYSTORE_FILE}}
          KEYSTORE_PROPERTIES: ${{secrets.KEYSTORE_PROPERTIES}}
        run: |
          echo -n "$KEYSTORE_FILE" | base64 -d > "release.jks"
          echo -n "$KEYSTORE_PROPERTIES" | base64 -d > "key.properties"

      - name: Build
        run: ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-android
          path: ./build/outputs/apk/release/*.apk
