name: Android

on:
  push:
    branches: [ korge ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://docs.korge.org/korge/deployment/desktop
      # Linux dependencies are also required for Android
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install freeglut3-dev libopenal-dev

      - name: Build
        run: ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-android
          path: ./build/outputs/apk/release/*.apk
