name: Linux

on:
  push:
    branches: [ korge ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://docs.korge.org/korge/deployment/desktop
      - name: Install dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install freeglut3-dev libopenal-dev

      - name: Build
        run: ./gradlew linkReleaseExecutableLinuxX64

      - name: Test
        run: ./gradlew linuxX64Test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-linux
          path: ./build/bin/linuxX64/releaseExecutable/
