name: macOS

on: [ push, pull_request ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Test
        run: ./gradlew macosX64Test

      - name: Build
        run: ./gradlew packageMacosX64AppRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-macos
          path: ./build/*.app
