name: MinGW

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Test
        run: ./gradlew mingwX64Test

      - name: Build
        run: ./gradlew linkReleaseExecutableMingwX64

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-mingw
          path: ./build/bin/mingwX64/releaseExecutable/
