name: Web (JS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew jsBrowserDistribution

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./build/distributions
          cname: ubongo.kraxarn.com

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubongo-js
          path: ./build/distributions
